version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unsubmy-email-backend
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./client_secret.json:/app/client_secret.json:ro
      - unsubmy-db:/app/instance
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true

volumes:
  unsubmy-db: 